airports = {"yga":"goroka",
"aba":"barter island",
"awt":"fort wainwright",
"alu":"cape lisburne",
"piz":"point lay",
"hto":"hilo",
"orl":"orlando",
"abt":"bettles",
"acl":"clear mews",
"aim":"indian mountains",
"fyu":"fort yukon",
"asv":"sparrevohn",
"afr":"fort richardson",
"atl":"tatalina",
"acz":"cape romanzof",
"bed":"bedford",
"asn":"st. paul island",
"aeh":"cape newenham",
"apb":"point barrow",
"ail":"iliamna",
"apm":"port moller",
"abm":"big mountain",
"osc":"oscoda",
"oar":"fort ord",
"mhr":"sacramento",
"bys":"fort irwin",
"nxp":"twenty nine palms",
"fsm":"fort smith",
"amr":"anchorage",
"gnt":"grants",
"pnc":"ponca city",
"svn":"hunter aaf",
"gfk":"grand forks",
"pbf":"pine bluff",
"nse":"milton",
"hhn":"hana",
"prc":"prescott",
"ttn":"trenton",
"bos":"boston",
"suu":"fairfield",
"rme":"rome",
"env":"wendover",
"bfm":"mobile",
"oak":"oakland",
"oma":"omaha",
"now":"port angeles",
"hog":"kahului",
"ict":"wichita",
"mci":"kansas city",
"msn":"madison",
"adl":"dillingham",
"hro":"harrison",
"phx":"phoenix",
"bgr":"bangor",
"fxe":"fort lauderdale",
"ggg":"longview",
"and":"andersen",
"geg":"spokane",
"hwo":"hollywood",
"sfo":"san francisco",
"ctb":"cutbank",
"ara":"louisiana",
"gnv":"gainesville",
"mem":"memphis",
"dug":"douglas",
"abi":"delta junction",
"cnw":"waco",
"ant":"annette island",
"car":"caribou",
"lrf":"jacksonville",
"hua":"redstone",
"pob":"fort bragg",
"dht":"dalhart",
"dlf":"del rio",
"lax":"los angeles",
"anb":"anniston",
"cle":"cleveland",
"dov":"dover",
"cvg":"cincinnati",
"fme":"fort meade",
"nid":"china lake",
"hon":"huron",
"ajn":"juneau",
"lft":"lafayette",
"ewr":"newark",
"boi":"boise",
"ins":"indian springs",
"gck":"garden city",
"mot":"minot",
"hhi":"wahiawa",
"mxf":"montgomery",
"rbm":"robinson",
"dal":"dallas",
"fcs":"fort carson",
"hln":"helena",
"nkx":"miramar",
"luf":"phoenix",
"hrt":"mary esther",
"hhr":"hawthorne",
"hul":"houlton",
"end":"enid",
"ntd":"point mugu",
"edw":"edwards afb",
"lch":"lake charles",
"hko":"kona",
"myr":"myrtle beach",
"nlc":"lemoore",
"ack":"nantucket",
"faf":"fort eustis",
"hop":"hopkinsville",
"dca":"washington",
"nhk":"patuxent river",
"psx":"palacios",
"byh":"blytheville",
"acy":"atlantic city",
"tik":"oklahoma city",
"ecg":"elizabeth city",
"pub":"pueblo",
"pqi":"presque isle",
"grf":"fort lewis",
"adq":"kodiak",
"hup":"opolu",
"fll":"fort lauderdale",
"mko":"muskogee",
"inl":"international falls",
"slc":"salt lake city",
"cds":"childress",
"bix":"biloxi",
"lsf":"fort benning",
"nqi":"kingsville",
"fri":"fort riley",
"mdt":"harrisburg",
"lnk":"lincoln",
"lan":"lansing",
"hmu":"kamuela",
"mss":"massena",
"hky":"hickory",
"spg":"st. petersburg",
"fmy":"fort myers",
"iah":"houston",
"mlt":"millinocket",
"adw":"camp springs",
"int":"winston-salem",
"vcv":"victorville",
"cew":"crestview",
"gtb":"fort drum",
"phn":"port huron",
"bfl":"bakersfield",
"elp":"el paso",
"hrl":"harlingen",
"cae":"columbia",
"dma":"tucson",
"npa":"pensacola",
"pns":"pensacola",
"rdr":"red river",
"hou":"houston",
"bkf":"buckley",
"aor":"northway",
"aaq":"palmer",
"pit":"pittsburgh",
"abr":"barrow",
"efd":"houston",
"nuw":"whidbey island",
"ali":"alice",
"vad":"valdosta",
"mia":"miami",
"sea":"seattle",
"cha":"chattanooga",
"bdr":"stratford",
"jan":"jackson",
"gls":"galveston",
"lgb":"long beach",
"hdh":"dillingham",
"ipt":"williamsport",
"ind":"indianapolis",
"szl":"knobnoster",
"akr":"akron",
"gwo":"greenwood",
"hpn":"white plains",
"fok":"west hampton beach",
"jbr":"jonesboro",
"tnx":"tonopah",
"lna":"west palm beach",
"nzy":"san diego",
"bif":"el paso",
"nyl":"yuma",
"cnm":"carlsbad",
"dlh":"duluth",
"abe":"bethel",
"lou":"louisville",
"fhu":"fort huachuca",
"hli":"lihue",
"huf":"terre haute",
"hvr":"havre",
"mwh":"grant county airport",
"mpv":"montpelier",
"nsi":"san nicolas island",
"ric":"richmond",
"shv":"shreveport",
"acv":"cordova",
"orf":"norfolk",
"bpt":"beaumont",
"sav":"savannah",
"hif":"ogden",
"aom":"nome",
"spb":"san luis",
"pie":"st. petersburg",
"mnm":"macon",
"cxo":"conroe",
"asc":"deadhorse",
"sat":"san antonio",
"roc":"rochester",
"cof":"coco beach",
"teb":"teterboro",
"rca":"rapid city",
"rdu":"raleigh-durham",
"day":"dayton",
"aen":"kenai",
"mlc":"mcalester",
"iag":"niagara falls",
"cfd":"bryan",
"lhw":"wright",
"phf":"newport news",
"esf":"alexandria",
"lts":"altus",
"tus":"tucson",
"mib":"minot",
"bab":"marysville",
"ikk":"kankakee",
"gsb":"goldsboro",
"pvd":"providence",
"sby":"salisbury",
"riu":"rancho murieta",
"bur":"burbank",
"dtw":"detroit",
"tpa":"tampa",
"pmb":"pembina",
"poe":"fort polk",
"aei":"fairbanks",
"hib":"hibbing",
"lfk":"lufkin",
"maf":"midland",
"grb":"green bay",
"adm":"ardmore",
"wri":"wrightstown",
"nkt":"cherry point",
"sbo":"santa barbara",
"ags":"bush field",
"isn":"williston",
"lit":"little rock",
"swf":"newburgh",
"bde":"baudette",
"sac":"sacramento",
"aho":"homer",
"tbn":"fort leonardwood",
"mge":"marietta",
"ska":"spokane",
"htl":"houghton lake",
"pam":"panama city",
"dfw":"dallas-fort worth",
"mlb":"melbourne",
"tcm":"tacoma",
"aus":"austin",
"lck":"columbus",
"saw":"gwinn",
"tys":"knoxville",
"hlr":"fort hood",
"stl":"st. louis",
"miv":"millville",
"sps":"wichita falls",
"luk":"cincinnati",
"atl":"atlanta",
"mer":"merced",
"mcc":"sacramento",
"grr":"grand rapids",
"ink":"wink",
"fat":"fresno",
"vrb":"vero beach",
"ipl":"imperial",
"bna":"nashville",
"lrd":"laredo",
"aed":"anchorage",
"aot":"kotzebue",
"aoo":"altoona",
"dys":"abilene",
"eld":"el dorado",
"lga":"new york",
"tlh":"tallahassee",
"dpa":"west chicago",
"act":"waco",
"aug":"augusta",
"inj":"hillsboro",
"nip":"jacksonville",
"mkl":"jackson",
"hmk":"molokai",
"ftk":"fort knox",
"nca":"jacksonville",
"sjt":"san angelo",
"cxl":"calexico",
"cic":"chico",
"btv":"burlington",
"jax":"jacksonville",
"dro":"durango",
"iad":"washington",
"cll":"college station",
"sff":"spokane",
"mke":"milwaukee",
"abi":"abilene",
"cou":"columbia",
"pdx":"portland",
"tnt":"miami",
"pbi":"west palm beach",
"ftw":"fort worth",
"ogs":"ogdensburg",
"fmh":"falmouth",
"bfi":"seattle",
"skf":"san antonio",
"hnl":"honolulu",
"dsm":"des moines",
"ewn":"new bern",
"san":"san diego",
"mlu":"monroe",
"ssc":"sumter",
"ont":"ontario",
"gvt":"greenvile",
"row":"roswell",
"det":"detroit",
"bro":"brownsville",
"dhn":"dothan",
"wwd":"wildwood",
"nfl":"fallon",
"mtc":"mount clemens",
"fmn":"farmington",
"crp":"corpus christi",
"syr":"syracuse",
"nqx":"key west",
"mdw":"chicago",
"sjc":"san jose",
"hob":"hobbs",
"pne":"philadelphia",
"den":"denver",
"phl":"philadelphia",
"sux":"sioux city",
"mcn":"macon",
"tcs":"truth or consequences",
"pmd":"palmdale",
"rnd":"san antonio",
"njk":"el centro",
"cmh":"columbus",
"fyv":"fayetteville",
"fsi":"fort sill",
"pnm":"princeton",
"ffo":"dayton",
"aga":"galena",
"chd":"chandler",
"mwl":"mineral wells",
"iab":"wichita",
"nbg":"new orleans",
"arw":"beaufort",
"txk":"texarkana",
"pbg":"plattsburgh",
"apg":"aberdeen",
"tcc":"tucumcari",
"anc":"anchorage",
"grk":"killeen",
"zun":"zuni pueblo",
"bli":"bellingham",
"nqa":"millington",
"ekn":"elkins",
"hfd":"hartford",
"sfz":"smithfield",
"mob":"mobile",
"nuq":"mountain view",
"saf":"santa fe",
"hbk":"barking sands",
"dri":"deridder",
"hsf":"bradshaw field",
"ols":"nogales",
"mcf":"tampa",
"blv":"belleville",
"opf":"miami",
"drt":"del rio",
"rsw":"fort myers",
"akn":"king salmon",
"mui":"muir",
"hjh":"lahania-kapalua",
"jfk":"new york",
"hst":"homestead",
"ral":"riverside",
"flv":"fort leavenworth",
"wal":"wallops island",
"hmn":"alamogordo",
"nxx":"willow grove",
"cys":"cheyenne",
"sck":"stockton",
"chs":"charleston",
"rno":"reno",
"akt":"ketchikan",
"yip":"detroit",
"vbg":"lompoc",
"bhm":"birmingham",
"nel":"lakehurst",
"asy":"shemya",
"lsv":"las vegas",
"riv":"riverside",
"mod":"modesto",
"smf":"sacramento",
"ugn":"chicago",
"cos":"colorado springs",
"buf":"buffalo",
"sky":"sandusky",
"pae":"everett",
"muo":"mountain home",
"cdc":"cedar city",
"bdl":"windsor locks",
"mfe":"mcallen",
"ngu":"norfolk",
"cef":"chicopee falls",
"lbb":"lubbock",
"ord":"chicago",
"bct":"boca raton",
"afa":"fairbanks",
"nyg":"quantico",
"cvs":"clovis",
"hng":"kaneohe bay",
"off":"omaha",
"agk":"gulkana",
"art":"watertown",
"psp":"palm springs",
"ama":"amarillo",
"fod":"fort dodge",
"bad":"shreveport",
"foe":"topeka",
"cot":"cotulla",
"ilm":"wilmington",
"btr":"baton rouge",
"nmm":"meridian",
"tyr":"tyler",
"bwi":"baltimore",
"hbr":"hobart",
"hny":"lanai",
"aex":"alexandria",
"wsd":"white sands",
"acd":"cold bay",
"tul":"tulsa",
"asi":"sitka",
"isp":"islip",
"msp":"minneapolis",
"ilg":"wilmington",
"adu":"unalaska",
"msy":"new orleans",
"pwm":"portland",
"okc":"oklahoma city",
"alb":"albany",
"avd":"valdez",
"lfi":"hampton",
"sna":"santa ana",
"cbm":"colombus",
"tmb":"kendall-tamiami",
"ntu":"oceana",
"gus":"peru",
"cpr":"casper",
"vps":"valparaiso",
"sem":"selma",
"eyw":"key west",
"clt":"charlotte",
"las":"las vegas",
"mco":"orlando",
"flo":"florence",
"gtf":"great falls",
"yng":"youngstown",
"afb":"fort wainwright",
"mmv":"mackminnville",
"wrb":"macon",
"puw":"pullman",
"lws":"lewiston",
"elm":"elmira",
"ith":"ithaca",
"mry":"monterey",
"sba":"santa barbara",
"dab":"daytona beach",
"jrb":"new york",
"atk":"talkeetna",
"hvn":"new haven",
"avl":"asheville",
"gso":"greensboro",
"fsd":"sioux falls",
"mht":"manchester nh",
"apf":"naples",
"sdf":"louisville",
"cho":"charlottesville va",
"roa":"roanoke va",
"lex":"lexington ky",
"evv":"evansville",
"abq":"albuquerque",
"bzn":"bozeman",
"bil":"billings",
"btm":"butte",
"tvc":"traverse city",
"bhb":"bar harbor",
"rkd":"rockland",
"jac":"jacksn hole",
"rfd":"rockford",
"gsp":"greenville",
"bmi":"bloomington",
"gpt":"gulfport",
"azo":"kalamazoo",
"tol":"toledo",
"fwa":"fort wayne",
"dec":"decatur",
"cid":"cedar rapids",
"lse":"la crosse",
"cwa":"wassau",
"pia":"peoria",
"atw":"appleton",
"rst":"rochester",
"cmi":"champaign",
"mhk":"manhattan",
"fkl":"franklin",
"gjt":"grand junction",
"sgu":"saint george",
"dwh":"houston",
"srq":"sarasota",
"vny":"van nuys",
"mli":"moline",
"pfn":"panama city",
"bis":"bismarck",
"tex":"telluride",
"rap":"rapid city",
"crq":"carlsbad",
"fnt":"flint",
"rdd":"redding",
"eug":"eugene",
"ida":"idaho falls",
"mfr":"medford",
"rdm":"redmond-bend",
"cak":"akron",
"hsv":"huntsville",
"pkb":"arkrsburg",
"mgm":"ontomery",
"tri":"ristol",
"pah":"aducah",
"pga":"page",
"gpi":"kalispell",
"mbs":"saginaw",
"bgm":"binghamton",
"blh":"blythe",
"apg":"petersburg",
"sfb":"sanford",
"jst":"johnstown",
"mso":"missoula",
"gcn":"grand canyon",
"sgr":"sugar land",
"apa":"denver",
"cvn":"clovis",
"fst":"fort stockton",
"lvs":"las vegas",
"iws":"houston",
"lhx":"la junta",
"lru":"las cruces",
"bkd":"breckenridge",
"tpl":"temple",
"oza":"ozona",
"ege":"vail",
"cgf":"richmond heights",
"mfd":"mansfield",
"csg":"columbus",
"law":"lawton",
"fnl":"fort collins",
"flg":"flagstaff",
"tvl":"south lake tahoe",
"twf":"twin falls",
"mvy":"vineyard haven ma",
"con":"concord nh",
"gon":"groton ct",
"stc":"saint cloud",
"gtr":"columbus mississippi",
"hqm":"hoquiam",
"eri":"erie",
"hya":"barnstable",
"sez":"sedona",
"mgw":"morgantown",
"crw":"charleston",
"avp":"scranton",
"bji":"bemidji",
"far":"fargo",
"mkc":"kansas city",
"gcc":"gillette",
"nzj":"santa ana",
"unv":"state college pennsylvania",
"mei":"meridian",
"spi":"springfield",
"cez":"cortez",
"hdn":"hayden",
"gup":"gallup",
"lbl":"liberal",
"laa":"lamar",
"gld":"goodland",
"cod":"cody",
"sgf":"springfield",
"jln":"joplin",
"abe":"allentown",
"xna":"bentonville",
"sbn":"south bend",
"smd":"fort wayne in",
"acv":"arcata ca",
"oaj":"jacksonville nc",
"tcl":"tuscaloosa al",
"dbq":"dubuque ia",
"abr":"aberdeen",
"aby":"albany",
"ahn":"athens",
"alm":"alamogordo",
"alo":"waterloo",
"alw":"walla walla",
"apn":"alpena",
"aty":"watertown",
"bfd":"bradford",
"bff":"scottsbluff",
"bkw":"beckley",
"bqk":"brunswick",
"brl":"burlington",
"cec":"crescent city",
"cgi":"cape girardeau",
"ciu":"sault ste marie",
"ckb":"clarksburg",
"clm":"port angeles",
"cmx":"hancock",
"ddc":"dodge city",
"duj":"du bois",
"eau":"eau claire",
"eko":"elko",
"ewb":"new bedford",
"fay":"fayetteville",
"ggw":"glasgow",
"gri":"grand island",
"hot":"hot springs",
"hts":"huntington",
"irk":"kirksville",
"jms":"jamestown",
"lar":"laramie",
"lbe":"latrobe",
"lbf":"north platte",
"leb":"lebanon",
"lmt":"klamath falls",
"lns":"lancaster",
"lwt":"lewistown",
"lyh":"lynchburg",
"mkg":"muskegon",
"mls":"miles city",
"msl":"muscle shoals",
"oth":"north bend",
"owb":"owensboro",
"pib":"laurel",
"pih":"pocatello",
"pir":"pierre",
"pln":"pellston",
"psm":"portsmouth",
"rdg":"reading",
"rhi":"rhinelander",
"rks":"rock springs",
"rut":"rutland",
"sbp":"san luis obispo",
"shr":"sheridan",
"slk":"saranac lake",
"sln":"salina",
"smx":"santa maria",
"tup":"tupelo",
"uin":"quincy",
"vct":"victoria",
"vld":"valdosta",
"wrl":"worland",
"ykm":"yakima",
"adk":"adak island",
"ags":"gustavus",
"agy":"skagway",
"ahc":"holy cross",
"ahn":"haines",
"alg":"kalskag",
"amc":"mcgrath",
"amo":"mountain village",
"ani":"aniak",
"ava":"chevak",
"awg":"wrangell",
"hlu":"molokai",
"blf":"bluefield",
"glh":"greenville",
"psc":"pasco",
"kqa":"akutan",
"orh":"worcester",
"pwt":"bremerton",
"spw":"spencer",
"jef":"jefferson city",
"pvc":"provincetown",
"ful":"fullerton",
"jqf":"concord",
"sun":"hailey",
"mcw":"mason city",
"iwa":"mesa",
"akp":"anaktuvuk pass",
"anv":"anvik",
"atq":"atqasuk",
"agm":"gambell",
"ahp":"hooper bay",
"akv":"kaltag",
"asm":"st mary's",
"avl":"kivalina",
"amy":"mekoryuk",
"ary":"ruby",
"ash":"shishmaref",
"asa":"savoonga",
"awn":"noatak",
"arc":"arctic village",
"apc":"port clarence",
"hgr":"hagerstown",
"asd":"sand point",
"ade":"deering",
"aig":"igiugig",
"anw":"new stuyahok",
"avc":"king cove",
"aph":"port heiden",
"atg":"togiak village",
"esc":"escanaba",
"aya":"yakutat",
"mwa":"marion",
"imt":"iron mountain",
"mqt":"marquette",
"fal":"allakaket",
"mgc":"michigan city",
"awd":"seward",
"ckc":"grand marais",
"auw":"wausau",
"mie":"muncie",
"laf":"lafayette",
"geo":"georgetown",
"vgt":"las vegas",
"enw":"kenosha",
"mtj":"montrose co",
"riw":"riverton wy",
"pdt":"pendleton",
"osh":"oshkosh",
"eat":"wenatchee",
"nfw":"dallas",
"gyy":"gary",
"brd":"brainerd",
"lwb":"lewisburg",
"pgv":"greenville",
"ack":"chefornak",
"oxr":"oxnard",
"bbg":"branson",
"sch":"scotia ny",
"sgj":"st. augustine airport",
"sts":"santa rosa",
"ism":"kissimmee",
"lcq":"lake city",
"ded":"deland",
"lgu":"logan",
"bmc":"brigham city",
"mld":"malad city",
"ase":"aspen",
"erv":"kerrville",
"ged":"georgetown",
"gbd":"great bend",
"hys":"hays",
"sus":"null",
"elo":"ely",
"gpz":"grand rapids mn",
"tvf":"thief river falls",
"egv":"eagle river",
"arv":"minocqua - woodruff",
"ikv":"ankeny",
"ngp":"corpus christi",
"avx":"catalina island",
"mhv":"mojave",
"hut":"hutchinson",
"stj":"rosecrans",
"vok":"camp douglas",
"guc":"gunnison",
"toa":"torrance",
"mbl":"manistee",
"pgd":"punta gorda",
"fve":"frenchville",
"jhw":"jamestown",
"sme":"somerset",
"shd":"weyers cave",
"dvl":"devils lake",
"dik":"dickinson",
"sdy":"sidney",
"cdr":"chadron",
"aia":"alliance",
"mck":"mccook",
"mth":"marathon",
"gdv":"glendive",
"olf":"wolf point",
"wys":"west yellowstone",
"als":"alamosa",
"cny":"moab",
"ely":"ely",
"vel":"vernal",
"srr":"ruidoso",
"sow":"show low",
"myl":"mccall",
"smn":"salmon",
"mmh":"mammoth lakes",
"fhr":"friday harbor",
"ors":"eastsound",
"ast":"astoria",
"onp":"newport",
"aem":"emmonak",
"aun":"unalakleet",
"aku":"kuparuk",
"ahx":"shageluk",
"ach":"chuathbaluk",
"aqt":"nuiqsut",
"aee":"eek",
"fka":"kasigluk",
"fkw":"kwethluk",
"agg":"kwigillingok",
"adm":"marshall",
"ars":"russian mission",
"ajz":"koliganek",
"amb":"manokotak",
"aci":"chalkyitsik",
"aeg":"eagle",
"ahu":"hughes",
"ahl":"huslia",
"anu":"nulato",
"ave":"venetie",
"awb":"beaver",
"ace":"central",
"agh":"shungnak",
"iyk":"inyokern",
"vis":"visalia",
"mce":"merced",
"gyr":"goodyear",
"agn":"angoon",
"ael":"elfin cove",
"anr":"funter bay",
"aoh":"hoonah",
"afe":"kake",
"amm":"metakatla",
"ahy":"hydaburg",
"aii":"egegik",
"ape":"perryville",
"apn":"pilot point",
"fws":"south naknek",
"akh":"akhiok",
"aky":"karluk",
"alb":"larsen bay",
"afm":"ambler",
"abl":"buckland",
"aik":"kiana",
"aob":"kobuk",
"fno":"noorvik",
"ask":"selawik",
"fkt":"brevig mission",
"fel":"elim",
"agl":"golovin",
"ate":"teller",
"aiw":"wales",
"awm":"white mountain",
"akk":"koyuk",
"amk":"st. michael",
"fsh":"shaktoolik",
"atc":"tin city",
"aak":"atka",
"ako":"nikolski",
"acy":"yakataga",
"auk":"alakanuk",
"aki":"kipnuk",
"akf":"false pass",
"aou":"nelson lagoon",
"aal":"cold bay",
"akw":"klawock",
"aqh":"quinhagak",
"fko":"kotlik",
"fku":"koyukuk",
"acm":"scammon bay",
"ano":"nondalton",
"ady":"kongiganak",
"afs":"nikolai",
"fak":"akiak",
"awi":"wainwright",
"fcb":"chenega",
"fto":"tok",
"acr":"circle",
"asl":"sleetmute",
"ahv":"healy",
"aqc":"klawock",
"amh":"lake minchumina",
"aml":"manley hot springs",
"mrb":"martinsburg",
"uza":"rock hill",
"agc":"pittsburgh",
"vqq":"jacksonville",
"fty":"atlanta",
"osu":"columbus",
"ads":"addison",
"dts":"destin",
"iso":"kinston",
"ffa":"kill devil hills",
"pvu":"provo",
"sbs":"steamboat springs",
"dta":"delta",
"rif":"richfield",
"puc":"price",
"lam":"los alamos",
"hii":"lake havasu city",
"inw":"winslow",
"dgl":"douglas",
"bow":"bartow",
"lvk":"livermore",
"mpi":"mariposa",
"trm":"palm springs",
"smo":"santa monica",
"udd":"palm springs",
"sdl":"scottsdale",
"olm":"olympia",
"dwa":"davis-woodland-winters",
"ril":"rifle",
"saa":"araoga",
"pdk":"atlanta",
"bmg":"bloomington",
"sua":"stuart",
"mmu":"morristown",
"apc":"napa",
"sdm":"san diego",
"vnc":"venice",
"phk":"pahokee",
"ecp":"panama city",
"sbd":"san bernardino",
"sql":"san carlos",
"rwi":"rocky mount",
"awr":"whittier",
"asx":"soldotna",
"see":"el cajon",
"nuc":"san clemente island",
"trk":"truckee",
"ryy":"atlanta",
"lvm":"livingston-montana",
"biv":"holland",
"jra":"new york",
"lal":"lakeland",
"idl":"new york",
"pcw":"port clinton",
"mgy":"dayton",
"rid":"richmond",
"fdy":"findley",
"spf":"spearfish-south dakota",
"olv":"olive branch",
"bjc":"broomfield-co",
"sle":"salem",
"uta":"tunica",
"mwc":"milwaukee",
"jvl":"janesville",
"gky":"arlington",
"lzu":"lawrenceville",
"bwg":"bowling green",
"rvs":"tulsa",
"bce":"bryce canyon",
"buy":"burlington",
"ixd":"olathe",
"esn":"easton",
"myv":"yuba city",
"duc":"duncan",
"uva":"uvalde",
"lot":"lockport",
"ccr":"concord",
"uni":"athens",
"sgh":"springfield",
"top":"topeka",
"mqy":"smyrna",
"uos":"sewanee",
"tki":"allas",
"pwk":"chicago-wheeling",
"kls":"kelso",
"iln":"wilmington",
"avq":"tucson",
"cgz":"casa grande",
"bxk":"buckeye",
"mmi":"athens",
"stk":"sterling",
"rwl":"rawlins",
"cdw":"caldwell",
"aiz":"kaiser lake ozark",
"tvi":"thomasville",
"hnd":"henderson",
"tma":"tifton",
"dvt":"phoenix ",
"frg":"farmingdale",
"hdo":"hondo",
"ain":"mckinley park",
"alh":"anchorage",
"apr":"prospect creek",
"hlg":"wheeling",
"fzg":"fitzgerald",
"rkp":"rockport",
"ckf":"cordele",
"omn":"ormond beach",
"ttd":"troutdale",
"hio":"hillsboro",
"bdn":"bend",
"bno":"burns",
"rbl":"red bluff",
"dvo":"novato",
"lkv":"lakeview",
"tmk":"tillamook",
"ono":"ontario",
"dls":"the dalles",
"gai":"gaithersburg",
"cvx":"charelvoix",
"xfl":"flagler",
"mvl":"morrisville",
"rbd":"dallas",
"wst":"washington county",
"bid":"block island",
"agt":"nightmute",
"aoo":"toksook bay",
"bge":"bainbridge",
"spz":"silver springs",
"whp":"los angeles",
"mae":"madera",
"aaf":"apalachicola",
"dqh":"douglas",
"fpr":"fort pierce",
"tan":"taunton",
"pym":"plymouth",
"oqu":"north kingstown",
"owd":"norwood",
"baf":"westfield",
"ijd":"willimantic",
"mgj":"montgomery",
"cxy":"harrisburg",
"ghg":"marshfield",
"dxr":"danbury",
"ash":"nashua",
"lwm":"lawrence",
"oxc":"oxford",
"fit":"fitchburg",
"vpc":"cartersville",
"pyp":"centre",
"rmg":"rome",
"gad":"gadsden",
"dkx":"knoxville",
"wdr":"winder",
"jyl":"sylvania",
"dnn":"dalton",
"ctj":"carrollton",
"lgc":"lagrange",
"mlj":"milledgeville",
"pim":"pine mountain",
"ffc":"atlanta",
"gvl":"gainesville",
"phd":"new philadelpha",
"udg":"darlington",
"hxd":"hilton head island",
"dnl":"augusta",
"mrn":"morganton",
"pbx":"pikeville",
"toc":"toccoa",
"afw":"fort worth",
"lwc":"lawrence",
"egt":"wellington",
"pmp":"pompano beach",
"eet":"alabaster",
"ump":"indianapolis",
"loz":"london",
"fbg":"fredericksburg",
"rac":"racine",
"rei":"redlands",
"rir":"riverside",
"tiw":"tacoma",
"jka":"gulf shores",
"hzl":"hazleton",
"cbe":"cumberland",
"lnr":"lone rock",
"pbh":"phillips",
"eft":"monroe",
"jot":"joliet",
"vys":"peru",
"jxn":"jackson",
"vvs":"connellsville",
"hmz":"bedford",
"lom":"philadelphia",
"obe":"okeechobee",
"sef":"sebring",
"avo":"avon park",
"gif":"winter haven",
"zph":"zephyrhills",
"ocf":"ocala",
"jes":"jesup",
"cco":"newnan",
"hqu":"thomson",
"aik":"aiken",
"cdn":"camden",
"lbt":"lumberton",
"sop":"pinehurst-southern pines",
"rcz":"rockingham",
"dll":"baraboo",
"svh":"statesville",
"buu":"burlington",
"lhv":"lock haven",
"pjc":"zelienople",
"lpr":"lorain-elyria",
"bkl":"cleveland",
"dkk":"dunkirk",
"vay":"mount holly",
"ldj":"linden",
"anq":"angola",
"asw":"warsaw",
"vnw":"van wert",
"rmy":"marshall",
"gvq":"batavia",
"clw":"clearwater",
"cgx":"chicago",
"jzp":"jasper",
"cre":"north myrtle beach",
"igq":"lansing",
"rnm":"ramona",
"oeb":"coldwater",
"wbw":"wilkes-barre",
"lnn":"willoughby",
"fft":"frankfort",
"lew":"lewiston",
"mky":"marco island airport",
"drm":"drummond island",
"gdw":"gladwin",
"lwa":"south haven",
"mfi":"marshfield",
"isw":"wisconsin rapids",
"cwi":"clinton",
"bvy":"beverly",
"pof":"poplar bluff",
"smq":"somerville",
"epm":"eastport",
"eok":"keokuk",
"stp":"st. paul",
"hao":"hamilton",
"fld":"fond du lac",
"pcz":"waupaca",
"ste":"stevens point",
"ery":"newberry",
"gqq":"galion",
"ckv":"clarksville",
"lpc":"lompoc",
"mqs":"coatesville",
"lkp":"lake placid",
"aoh":"lima",
"ssi":"brunswick",
"bvi":"beaver falls",
"gge":"georgetown",
"hdi":"cleveland",
"rnt":"renton",
"poc":"la verne",
"cty":"cross city",
"ceu":"clemson",
"bec":"wichita",
"czl":"calhoun",
"ajr":"cornelia",
"gtu":"georgetown",
"sny":"sidney",
"hjr":"kapolei",
"mdq":"huntsville",
"jyo":"leesburg",
"ane":"anoka",
"sdc":"williamson",
"bdu":"boulder",
"pao":"palo alto",
"ffz":"mesa",
"ptk":"pontiac",
"een":"keene",
"iow":"iowa city",
"mwm":"windom",
"anp":"annapolis",
"peq":"pecos",
"hbg":"hattiesburg",
"ykn":"yankton",
"hwd":"hayward",
"arb":"ann arbor",
"ngz":"alameda",
"lcr":"salt lake city",
"imm":"immokalee ",
"ptb":"petersburg",
"sbm":"sheboygan",
"mzj":"marana",
"geu":"glendale",
"sad":"safford",
"sik":"sikeston",
"gfl":"queensbury",
"cgc":"crystal river",
"mtn":"baltimore",
"lhm":"lincoln",
"fzi":"fostoria",
"izg":"fryeburg",
"new":"new orleans",
"coe":"coeur d'alene",
"bmt":"beaumont",
"dnv":"danville",
"tix":"titusville",
"aap":"houston",
"fcm":"eden prairie",
"ojc":"olathe",
"oqn":"west goshen township",
"hef":"manassas",
"lbx":"angleton",
"alj":"port alsworth",
"fdw":"winnsboro",
"daw":"rochester",
"ewk":"newton",
"hta":"columbus",
"fbr":"fort bridger",
"cls":"chehalis",
"evw":"evanston",
"lro":"mount pleasant",
"acj":"americus",
"euf":"eufala",
"mqi":"manteo",
"auo":"auburn",
"czg":"endicott",
"eky":"bessemer",
"mic":"crystal",
"dbn":"dublin",
"cvo":"corvallis",
"crt":"scranton",
"rst":"morristown",
"ogd":"ogden",
"rkr":"poteau",
"ako":"akron",
"shn":"shelton",
"ana":"napakiak",
"apk":"napaskiak",
"atj":"tok",
"dyl":"doylestown",
"ocw":"washington",
"swo":"stillwater",
"okm":"okmulgee",
"cuh":"cushing",
"csm":"clinton",
"wld":"winfield",
"pwa":"oklahoma city",
"dtn":"shreveport",
"sep":"stephenville",
"mnz":"hamilton",
"adh":"ada",
"hqz":"misquite",
"dto":"denton",
"edc":"austin",
"ryw":"lago vista",
"ukf":"north wilkesboro",
"jzi":"charleston",
"dan":"danville",
"cqw":"cheraw",
"chn":"wuchula",
"hyw":"conway",
"hbi":"asheboro",
"acz":"wallace",
"emv":"emporia",
"emt":"el monte",
"ssf":"stinson",
"jsv":"sallisaw",
"jas":"jasper",
"mrf":"marfa",
"ccb":"upland",
"iob":"mount sterling",
"ekm":"elkhart",
"cub":"columbia",
"gmj":"grove",
"mpr":"mc pherson",
"gyh":"greenville",
"pxe":"perry",
"hvs":"hartsville",
"igx":"chapel hill",
"sut":"oak island",
"fci":"richmond",
"hnz":"oxford",
"lee":"leesburg",
"cno":"chino",
"uyf":"london",
"prb":"paso robles",
"haf":"half moon bay",
"wjf":"lancaster",
"tdf":"roxboro",
"asn":"talladega",
"gmu":"greenville",
"mkt":"mankato",
"toi":"troy",
"scd":"sylacauga",
"edn":"enterprise",
"ryn":"tucson",
"alx":"alexander city",
"mmk":"meriden",
"rjd":"ridgely",
"uwl":"new castle",
"tqk":"scott city",
"hde":"holdredge",
"ptt":"pratt",
"ahq":"wahoo",
"lxn":"lexington",
"cbf":"council bluffs",
"okk":"kokomo",
"eha":"elkhart",
"ftg":"denver",
"gbg":"galesburg",
"guy":"guymon",
"mej":"meade",
"uls":"ulysses",
"idp":"independence",
"lqr":"larned",
"lzz":"lampasas",
"byy":"bay city",
"prx":"paris",
"cfv":"coffeyville",
"gxy":"greeley",
"uor":"oakley",
"fet":"fremont",
"lgd":"la grande",
"mpo":"mount pocono",
"ukt":"quakertown",
"bng":"banning",
"ofk":"norfolk  nebraska",
"awo":"arlington",
"tpf":"tampa",
"mtp":"montauk",
"vpz":"valparaiso in",
"ldm":"ludington",
"rhv":"san jose",
"cma":"camarillo - ca",
"wvi":"watsonville",
"cvh":"hollister",
"jgg":"williamsburg",
"mrt":"marysville",
"aln":"alton",
"axn":"alexandria",
"bak":"columbus",
"bbd":"brady",
"bih":"bishop",
"bke":"baker city",
"bpi":"big piney",
"bpk":"mountain home",
"btl":"battle creek",
"byi":"burley",
"ccy":"charles city",
"cnu":"chanute",
"crg":"jacksonville",
"csv":"crossville",
"daa":"fort belvoir",
"dag":"daggett",
"dmn":"deming",
"dra":"mercury",
"eed":"needles",
"egi":"crestview",
"eka":"eureka",
"hyi":"san marcos",
"hyr":"hayward",
"jct":"junction",
"llq":"monticello",
"lol":"lovelock",
"mbg":"mobridge",
"mcb":"mc comb",
"mdh":"murphysboro",
"mmt":"eastover",
"nhz":"brunswick",
"nrb":"mayport",
"ogb":"orangeburg",
"olu":"columbus",
"otm":"ottumwa",
"ozr":"ozark",
"pna":"pinedale",
"pou":"poughkeepsie",
"rnh":"new richmond",
"rsl":"russell",
"rwf":"redwood falls",
"sns":"salinas",
"soa":"sonora",
"suz":"benton",
"tph":"tonopah",
"uao":"aurora",
"uki":"ukiah",
"uox":"oxford",
"uts":"huntsville",
"vtn":"valentine",
"wmc":"winnemucca",
"wwr":"woodward",
"xmr":"cocoa beach",
"xta":"groom lake",
"zzv":"zanesville",
"ann":"nenana",
"aws":"wasilla",
"tcy":"tracy",
"tzr":"columbus",
"bvs":"skagit",
"apt":"jasper",
"gzh":"evergreen",
"dcu":"decatur",
"glw":"glasgow",
"lzd":"danielson",
"fig":"clearfield",
"rzl":"rensselaer",
"tbr":"statesboro",
"evb":"new smyrna beach",
"mrj":"ineral oint",
"etb":"est end",
"glr":"aylord",
"aid":"ndeson",
"pdc":"prairie du chien",
"vuj":"albemarle",
"exx":"lexington",
"aeg":"albuquerque",
"onm":"socorro",
"vbt":"bentonville",
"mtv":"martinsville",
"mwk":"mount airy",
"skx":"taos",
"rtn":"raton",
"rcx":"ladysmith",
"ppa":"pampa",
"owp":"sand springs",
"flp":"flippin",
"bgd":"borger",
"iza":"santa ynez",
"spa":"spartangurg",
"ppf":"parsons",
"ays":"waycross",
"psb":"philipsburg",
"pmh":"portsmouth",
"cxu":"camilla",
"fcl":"clarks point",
"szt":"sandpoint",
"vll":"troy",
"adg":"red dog",
"fks":"frankfort",
"slh":"cheboygan",
"jwn":"nashville",
"hsa":"bay st. louis",
"aso":"seldovia",
"jkl":"jackson",
"nbc":"beaufort",
"nfg":"oceanside",
"vdi":"vidalia",
"gdj":"granbury",
"fzy":"fulton",
"mhe":"mitchell"
}
